config/routes.rb
Rails.application.routes.draw do
	root 'enrollments#index'
  devise_for :users
  resources :enrollments
  resources :students
  resources :sections
  resources :courses
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/section.rb
class Section < ApplicationRecord
  validates :semester, :section_id, :course_id, presence: true
  validates :course_id, :section_id, numericality: {greater_than: 0}
  has_many :enrollments
  has_many :students, through: :enrollments
  belongs_to :course

  def numsem 
    "#{course.course_name} #{section_id} #{semester}"
  end

end

app/controllers/sections_controller.rb
class SectionsController < ApplicationController
  before_action :set_section, only: [:show, :edit, :update, :destroy]

  # GET /sections
  # GET /sections.json
  def index
  if params[:search]
   @sections = Section.where('section_id LIKE ?', "%#{params[:search]}%")
  else
   @sections = Section.all
 end
end

  # GET /sections/1
  # GET /sections/1.json
  def show
  end

  # GET /sections/new
  def new
    @section = Section.new
  end

  # GET /sections/1/edit
  def edit
  end

  # POST /sections
  # POST /sections.json
  def create
    @section = Section.new(section_params)

    respond_to do |format|
      if @section.save
        format.html { redirect_to @section, notice: 'Section was successfully created.' }
        format.json { render :show, status: :created, location: @section }
      else
        format.html { render :new }
        format.json { render json: @section.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /sections/1
  # PATCH/PUT /sections/1.json
  def update
    respond_to do |format|
      if @section.update(section_params)
        format.html { redirect_to @section, notice: 'Section was successfully updated.' }
        format.json { render :show, status: :ok, location: @section }
      else
        format.html { render :edit }
        format.json { render json: @section.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sections/1
  # DELETE /sections/1.json
  def destroy
    @section.destroy
    respond_to do |format|
      format.html { redirect_to sections_url, notice: 'Section was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_section
      @section = Section.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def section_params
      params.require(:section).permit(:semester, :section_id, :course_id, :room_number, :search)
    end
end

app/helpers/sections_helper.rb
module SectionsHelper
end

app/views/sections/_form.html.erb
<%= form_with(model: section, local: true) do |form| %>
  <% if section.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(section.errors.count, "error") %> prohibited this section from being saved:</h2>

      <ul>
      <% section.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :semester %>
    <%= form.text_field :semester, id: :section_semester %>
  </div>

  <div class="field">
    <%= form.label :section_id %>
    <%= form.number_field :section_id, id: :section_section_id %>
  </div>

  <div class="field">
    <%= form.label :course_id %>
    <%= form.collection_select :course_id, Course.order(:course_name), :id, :course_name, include_blank: true %>
  </div> 

  <div class="field">
    <%= form.label :room_number %>
    <%= form.text_field :room_number, id: :section_room_number %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/sections/edit.html.erb
<h1>Editing Section</h1>

<%= render 'form', section: @section %>

<%= link_to 'Show', @section %> |
<%= link_to 'Back', sections_path %>

app/views/sections/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Sections</h1>

<%= form_tag(sections_path, method: :get) do %>
  <%= text_field_tag :search %>
  <%= label_tag(:search, "Search for:") %>
  <%= submit_tag 'Search' %>
<% end %>

<table>
  <thead>
    <tr>
      <th>Semester</th>
      <th>Section</th>
      <th>Course</th>
      <th>Room number</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @sections.each do |section| %>
      <tr>
        <td><%= section.semester %></td>
        <td><%= section.section_id %></td>
        <td><%= section.course.course_name%></td>
        <td><%= section.room_number %></td>
        <td><%= link_to 'Show', section %></td>
        <td><%= link_to 'Edit', edit_section_path(section) %></td>
        <td><%= link_to 'Destroy', section, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Section', new_section_path %>

app/views/sections/new.html.erb
<h1>New Section</h1>

<%= render 'form', section: @section %>

<%= link_to 'Back', sections_path %>

app/views/sections/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Semester:</strong>
  <%= @section.semester %>
</p>

<p>
  <strong>Section:</strong>
  <%= @section.section_id %>
</p>

<p>
  <strong>Course:</strong>
  <%= @section.course.course_name %>
</p>

<p>
  <strong>Room number:</strong>
  <%= @section.room_number %>
</p>

<%= link_to 'Edit', edit_section_path(@section) %> |
<%= link_to 'Back', sections_path %>